version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: "${PROJECT_NAME}_postgres"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
  redis:
    image: redis:6.2-alpine
    container_name: "${PROJECT_NAME}_redis"
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - .env
volumes:
  db:
    driver: local
  redis:
    driver: local
