# Generated by Django 4.0.6 on 2022-07-15 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='images')),
                ('rotate_duration', models.FloatField(default=0)),
                ('modified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
